<?php
	//翻译字典

	return array(
		'ru'=>array(
			'New user'=>'Новый пользователь',
			'Shoping Guide'=>'Описание заказа',
			'Payment & Charge'=>'Оплатить и пополнить счет',
			'Order Instruction'=>'приказ руководства',
			'Transportation'=>'Доставка и таможня',
			'Customer Service'=>'Служба поддержки',
			'Tool/Help'=>'инструменты / помочь',
			'Place order'=>'заказ ',
			'Order Tutorial'=>'процесс заказа',
			'Registration & Setting'=>'Регистрация',
			'About lrise'=>'около lrise',
            'My Chinese Address'=>'Мой Китайская Адрес',
			'Customer Instruction'=>'Руководство пользователя',
			'Lrise Member Grade'=>'Класс члена Lrise',
			'Taobao Agent'=>'Taobao закупки',
			'Shopping tips'=>'торговый Примечания',
			'Purchasing notice'=>'уведомления о закупках',
			'Measurement help'=>'Помощь в размерах',
			'Taobao in English '=>'Taobao на английском языке',
			'Taobao на русский'=>'Taobao русский',
			'Taobao en español'=>'Taobao на испанском языке',
			'Add money'=>'подпитки',
			'Refund & Withdraw'=>'отменить и возмещение',
			'Charge policy'=>'Оплата заказа и другое',
			'Points & E-coupons'=>'Онлайн магазины',
			'Order cancellation'=>'аннулировать заказ',
			'Order status'=>'государственный заказ',
			'Submint delivery'=>'представить  платежей',
			'Delivery methods'=>'способ оплаты',
			'Shipping price'=>'стоимость перевозки',
			'Parcel tracking'=>'отслеживания посылки',
			'Customs'=>'о таможне',
			'Contact us'=>'Свяжитесь с нами',
			'Complaint & Claim'=>'жалобы и претензии',
			'Return policy'=>'возвращение политики',
			'FAQ'=>'Центр помощи',
			'Weight estimation'=>'вес оценки',
			'Size conversion'=>'размер преобразование',
			'Cost calculator'=>'расчет затрат',
			'Exchange rate'=>'обменных курсов',

		),
		'zh'=>array(
			'New user'=>'新手指南',
			'Shopping Guide'=>'购物指南',
			'Payment & Charge'=>'付费充值',
			'Order Instruction'=>'订单指南',
			'Transportation'=>'运输方式',
			'Customer Service'=>'联系客服',
			'Tool/Help'=>'工具/帮助',
			'Place order'=>'下订单',
			'Order Tutorial'=>'订单流程',
			'Registration & Setting'=>'注册与设置',
			'About lrise'=>'关于lrise',
            'My Chinese Address'=>'我的中国地址',
			'Customer Instruction'=>'用户指南',
			'Lrise Member Grade'=>'会员等级',
			'Taobao Agent'=>'淘宝代购',
			'Shopping tips'=>'购物须知',
			'Purchasing notice'=>'采购通知',
			'Measurement help'=>'测量帮助',
			'Taobao in English '=>'淘宝英文',
			'Taobao на русский'=>'淘宝俄文',
			'Taobao en español'=>'淘宝西班牙文',
			'Add money'=>'充值',
			'Refund & Withdraw'=>'取消与退款',
			'Charge policy'=>'收费政策',
			'Points & E-coupons'=>'积分与优惠卷',
			'Order cancellation'=>'取消订单',
			'Order status'=>'订单状态',
			'Submint delivery'=>'提交支付',
			'Delivery methods'=>'支付方式',
			'Shipping price'=>'运输价格',
			'Parcel tracking'=>'包裹跟踪',
			'Customs'=>'关于海关',
			'Contact us'=>'联系我们',
			'Complaint & Claim'=>'投诉和索赔',
			'Return policy'=>'退货政策',
			'FAQ'=>'帮助中心',
			'Weight estimation'=>'重量估算',
			'Size conversion'=>'尺码换算',
			'Cost calculator'=>'成本计算',
			'Exchange rate'=>'汇率换算',
			
		),

	);





?>