<?php
	//翻译字典

	return array(
		'ru'=>array(
			'New User'=>'Новый пользователь',
			'Shoping Guide'=>'Описание заказа',
			'Payment & Charge'=>'Оплатить и пополнить счет',
			'Order Instruction'=>'приказ руководства',
			'Transportation'=>'Доставка и таможня',
			'Customer Service'=>'Служба поддержки',
			'Tool/Help'=>'инструменты / помочь',
			'Place order'=>'заказ ',
			'Order Tutorial'=>'процесс заказа',
			'Registration & Setting'=>'Регистрация',
			'About Lrise'=>'O Lrise',
			'Customer Instruction'=>'Руководство пользователя',
			'Lrise Member Grade'=>'Класс члена Lrise',
			'Taobao Agent'=>'Taobao закупки',
			'Shopping tips'=>'торговый Примечания',
			'Purchasing notice'=>'уведомления о закупках',
			'Measurement help'=>'Помощь в размерах',
			'Taobao in English '=>'Taobao на английском языке',
			'Taobao на русский'=>'Taobao русский',
			'Taobao en español'=>'Taobao на испанском языке',
			'Add money'=>'подпитки',
			'Refund & Withdraw'=>'отменить и возмещение',
			'Charge Policy'=>'Оплата заказа и другое',
			'Points and E-coupons'=>'очков и E-купоны',
			'Order Cancellation'=>'аннулировать заказ',
			'Order Status'=>'государственный заказ',
			'Submit delivery'=>'представить  платежей',
			'Delivery Methods'=>'способ оплаты',
			'Shipping Price'=>'стоимость перевозки',
			'Parcel tracking'=>'отслеживания посылки',
			'Customs'=>'о таможне',
			'Contact us'=>'Свяжитесь с нами',
			'Complaint & Claim'=>'жалобы и претензии',
			'Return Policy'=>'возвращение политики',
			'FAQ'=>'Центр помощи',
			'Weight estimation'=>'вес оценки',
			'Size conversion'=>'размер преобразование',
			'Cost calculator'=>'расчет затрат',
			'Exchange rate'=>'обменных курсов',
			'My Chinese Address'=>'мой адрес в китае',
			'Making Payments'=>'в рассрочку',
			'Shipping & Delivery'=>'транспорт и доставка',
			'Personal Profile'=>' личные данные',
			'Other questions'=>'Другие вопросы',
			'Refund policy'=>'возвращение политики',
			'How to use Taobao in English'=>'как использовать английский taobao покупок в сети',
			'Lrise points and E-coupons'=>'Lrise очков и E-купоны',
			'Measurement Help'=>'измерение помощи',
			'Online stores'=>'интернет - магазин ',
			'Searching Words'=>'поиска язык',
			'Search Tips'=>'навыков поиска',
			'translate tools'=>'перевод средств',
			'Exchange Rate'=>'обменный курс',
			'Contact Us'=>'Свяжитесь с нами',
			'Chinese map'=>'карта китая',

		),
		'zh'=>array(
			'New User'=>'新手指南',
			'Shopping Guide'=>'购物指南',
			'Payment & Charge'=>'付费充值',
			'Order Instruction'=>'订单指南',
			'Transportation'=>'运输方式',
			'Customer Service'=>'联系客服',
			'Tool/Help'=>'工具/帮助',
			'Place order'=>'下订单',
			'Order Tutorial'=>'订单流程',
			'Registration & Setting'=>'注册与设置',
			'About Lrise'=>'关于Lrise',
			'Customer Instruction'=>'用户指南',
			'Lrise Member Grade'=>'会员等级',
			'Taobao Agent'=>'淘宝代购',
			'Shopping tips'=>'购物须知',
			'Purchasing notice'=>'采购通知',
			'Measurement help'=>'测量帮助',
			'Taobao in English '=>'淘宝英文',
			'Taobao на русский'=>'淘宝俄文',
			' Taobao en español'=>'淘宝西班牙文',
			'Add money'=>'充值',
			'Refund & Withdraw'=>'取消与退款',
			'Charge policy'=>'收费政策',
			'Points and E-coupons'=>'积分与优惠卷',
			'Order Cancellation'=>'取消订单',
			'Order Status'=>'订单状态',
			'Submit delivery'=>'提交支付',
			'Delivery Methods'=>'支付方式',
			'Shipping Price'=>'运输价格',
			'Parcel tracking'=>'包裹跟踪',
			'Customs'=>'关于海关',
			'Contact us'=>'联系我们',
			'Complaint & Claim'=>'投诉和索赔',
			'Return policy'=>'退货政策',
			'FAQ'=>'帮助中心',
			'Weight Estimation'=>'重量估算',
			'Size conversion'=>'尺码换算',
			'Cost calculator'=>'成本计算',
			'Exchange rate'=>'汇率换算',			
			'My Chinese Address'=>'我的中国地址',
			'Making Payments'=>'付款',
			'Shipping & Delivery'=>'运送与交付',
			'Personal Profile'=>'个人资料',
			'Other questions'=>'其他问题',
			'Refund policy'=>'退款政策',
			'How to use Taobao in English'=>'如何使用淘宝代购',
			'Lrise points and E-coupons'=>'Lrise积分和优惠券',
			'Measurement Help'=>'测量帮助',
			'Online stores'=>'在线商城',
			'Searching Words'=>'搜索关键词',
			'Search Tips'=>'搜索提示',
			'translate tools'=>'翻译软件',
			'Exchange Rate'=>'汇率换算',
			'Contact Us'=>'联系我们',
			'Chinese map'=>'中国地图',
			
		),

	);





?>